#!/usr/bin/env python3
"""Copy compact run evidence and media into a portable example directory."""
import argparse
import hashlib
import json
from pathlib import Path
import shutil


def main(source, destination):
    if destination.exists():
        raise FileExistsError(f'Choose a fresh example folder: {destination}')
    summary = json.loads((source/'summary.json').read_text())
    assert summary['co2_transport_enabled'] and summary['duration_s'] == 1800
    rendering = json.loads((source/'rendering.json').read_text())
    assert rendering['media_decode'] == 'PASS'
    paths = ['inputs.json','summary.json','timeseries.csv','transport_audit.csv','rendering.json','verification.json',
             'configs/source_hashes.json']
    paths += rendering['media']
    if 'renderer_source' in rendering: paths.append(rendering['renderer_source'])
    verification=json.loads((source/'verification.json').read_text())
    if 'auditor_source' in verification: paths.append(verification['auditor_source'])
    for name in paths:
        target = destination/name
        target.parent.mkdir(parents=True,exist_ok=True)
        shutil.copy2(source/name,target)
    text = '''# Example: operating chamber in WaterLily

Two 5-minute sealed / 10-minute unsealed cycles, 96 m³ nominal airspace,
three central fans and prescribed February 2025 C2 leaflet net uptake.

Open [the cycle video](videos/c2_202502_cycle.mp4) or
[the animated preview](videos/c2_202502_cycle.gif).
The five views include a [large 3D view](videos/chamber_3d.mp4), fan sections,
operation histories and leaflet sources. The coloured planes are sections
through the saved 3D field; dark arrows show native three-component velocity.

This compact example includes media, inputs, histories and numerical audits.
The full velocity/concentration arrays and frozen source are retained in the
local result bundle and regenerated by the commands in the project README.
Field paths inside summary.json therefore refer to that full bundle.

Status: **diagnostic, not experimentally validated**. Read the checks in
summary.json, including the airflow-to-scalar correction screen. Numerical wall
thickening and first-order transport affect mixing. Test success is separate
from scientific validation.
'''
    (destination/'README.md').write_text(text)
    sha = lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
    hashes={str(p.relative_to(destination)):sha(p) for p in destination.rglob('*') if p.is_file()}
    (destination/'manifest.json').write_text(json.dumps({'sha256':hashes},indent=2)+'\n')
    print(f'Exported {len(hashes)} files to {destination}')


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source',type=Path);parser.add_argument('destination',type=Path)
    args=parser.parse_args();main(args.source,args.destination)
